# Gunakan Node.js official image
FROM node:22

# Tentukan direktori kerja di container
WORKDIR /usr/src/app

# Salin package.json dan install dependencies
COPY package*.json ./
RUN npm install

# Salin seluruh kode aplikasi ke dalam container
COPY . .

# Ekspos port yang digunakan aplikasi
EXPOSE 3000

# Perintah untuk menjalankan aplikasi
CMD ["npm", "start"]
