version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=192.168.99.2 # Alamat IP komputer yang menjalankan PostgreSQL
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=node_user
      - DB_PORT=5432
    restart: always
